package com.fountainhome.streaming.ui;
import android.app.Dialog;
import android.content.Intent;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.ViewModelProvider;
import androidx.recyclerview.widget.*;
import com.bumptech.glide.Glide;
import com.fountainhome.streaming.R;
import com.fountainhome.streaming.api.Models;
import com.fountainhome.streaming.databinding.ActivityWatchBinding;
import com.fountainhome.streaming.download.DownloadManager2;
import com.fountainhome.streaming.service.*;
import com.fountainhome.streaming.ui.adapter.*;
import com.fountainhome.streaming.ui.player.PlayerActivity;
import com.fountainhome.streaming.ui.viewmodel.*;
import java.util.ArrayList;
import java.util.List;
public class WatchActivity extends AppCompatActivity {
    private ActivityWatchBinding b;private WatchViewModel vm;private ContentItem item;
    private String type;private int tmdbId,selSeason=1,selEpisode=1;
    private List<Models.Episode>eps=new ArrayList<>();
    @Override protected void onCreate(Bundle s){super.onCreate(s);b=ActivityWatchBinding.inflate(getLayoutInflater());setContentView(b.getRoot());type=getIntent().getStringExtra("type");tmdbId=getIntent().getIntExtra("id",0);vm=new ViewModelProvider(this).get(WatchViewModel.class);vm.getLoading().observe(this,l->b.loadingView.setVisibility(l?View.VISIBLE:View.GONE));vm.getContent().observe(this,ci->{if(ci==null)return;item=ci;populate(ci);});vm.getSeason().observe(this,sd->{if(sd==null)return;eps=sd.episodes!=null?sd.episodes:new ArrayList<>();populateEps();});vm.getSimilar().observe(this,items->{if(items==null||items.isEmpty()){b.similarSection.setVisibility(View.GONE);return;}b.similarSection.setVisibility(View.VISIBLE);ContentAdapter a=new ContentAdapter(sim->{Intent i=new Intent(this,WatchActivity.class);i.putExtra("type",sim.mediaType);i.putExtra("id",sim.id);startActivity(i);});b.similarRv.setLayoutManager(new LinearLayoutManager(this,LinearLayoutManager.HORIZONTAL,false));b.similarRv.setAdapter(a);a.submitList(items);});b.backBtn.setOnClickListener(v->finish());vm.load(type,tmdbId);}
    private void populate(ContentItem ci){Glide.with(this).load(SourceGenerator.imageUrl(ci.backdropPath,"w780")).centerCrop().into(b.backdropImage);Glide.with(this).load(SourceGenerator.imageUrl(ci.posterPath,"w342")).centerCrop().into(b.posterImage);b.titleText.setText(ci.displayTitle());StringBuilder m=new StringBuilder();if(!ci.year().isEmpty())m.append(ci.year());if(ci.runtime>0)m.append(" \u00b7 ").append(ci.runtime).append("m");if(ci.rating>0)m.append(" \u00b7 \u2605").append(String.format("%.1f",ci.rating));if("tv".equals(type)&&ci.numberOfSeasons>0)m.append(" \u00b7 ").append(ci.numberOfSeasons).append(" seasons");b.metaText.setText(m);if(ci.overview!=null){b.overviewText.setText(ci.overview);b.overviewText.setVisibility(View.VISIBLE);}if("tv".equals(type)){b.tvSection.setVisibility(View.VISIBLE);setupSeasons(ci.numberOfSeasons);}else b.tvSection.setVisibility(View.GONE);String[]srcs={"VidSrc","2Embed","AutoEmbed","SuperEmbed VIP"};ArrayAdapter<String>sa=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,srcs);sa.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);b.sourceSpinner.setAdapter(sa);String pref=AppPreferences.getSource(this);for(int i=0;i<srcs.length;i++)if(srcs[i].equals(pref)){b.sourceSpinner.setSelection(i);break;}b.sourceSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?>p,View v,int pos,long id){AppPreferences.setSource(WatchActivity.this,srcs[pos]);}public void onNothingSelected(AdapterView<?>p){}});refreshBtns(ci);b.favoriteBtn.setOnClickListener(v->{LibraryManager.toggleFavorite(this,ci);refreshBtns(ci);Toast.makeText(this,LibraryManager.isIn(this,ci.id,ci.mediaType,LibraryManager.FAVORITES)?"Added to favorites":"Removed",Toast.LENGTH_SHORT).show();});b.watchlistBtn.setOnClickListener(v->{boolean in=LibraryManager.isIn(this,ci.id,ci.mediaType,LibraryManager.WATCHLIST);if(in)LibraryManager.remove(this,ci.id,ci.mediaType,LibraryManager.WATCHLIST);else LibraryManager.add(this,ci,LibraryManager.WATCHLIST);refreshBtns(ci);});b.downloadBtn.setOnClickListener(v->{DownloadManager2.saveForOffline(this,ci);b.downloadBtn.setImageResource(R.drawable.ic_check);Toast.makeText(this,"Saved offline",Toast.LENGTH_SHORT).show();});b.shareBtn.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,ci.displayTitle()+" \u2014 Fountain Home");startActivity(Intent.createChooser(i,"Share via"));});b.playBtn.setOnClickListener(v->openPlayer(ci));long pos=WatchProgress.get(this,tmdbId,type,selSeason,selEpisode);if(pos>10000){b.resumeBtn.setVisibility(View.VISIBLE);b.resumeBtn.setOnClickListener(v->openPlayer(ci));}if("tv".equals(type)){b.episodeMenuBtn.setVisibility(View.VISIBLE);b.episodeMenuBtn.setOnClickListener(v->showMenu(ci));}}
    private void setupSeasons(int count){final int total=count<=0?1:count;b.seasonButtonsContainer.removeAllViews();for(int s=1;s<=total;s++){final int sn=s;TextView btn=new TextView(this);btn.setText("S"+s);btn.setPadding(24,12,24,12);btn.setTextColor(s==selSeason?AppPreferences.getAccentColor(this):0xFFAAAAAA);btn.setTextSize(13);btn.setOnClickListener(v->{selSeason=sn;selEpisode=1;vm.loadSeason(tmdbId,sn);setupSeasons(total);});b.seasonButtonsContainer.addView(btn);}}
    private void populateEps(){EpisodeAdapter a=new EpisodeAdapter(eps,(ep,num)->{selEpisode=num;openPlayer(item);},tmdbId,type,selSeason,this);b.episodeListRv.setLayoutManager(new LinearLayoutManager(this));b.episodeListRv.setAdapter(a);}
    private void showMenu(ContentItem ci){Dialog d=new Dialog(this,R.style.Theme_FountainHome);d.requestWindowFeature(Window.FEATURE_NO_TITLE);d.setContentView(R.layout.dialog_episode_menu);if(d.getWindow()!=null)d.getWindow().setLayout(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT);RecyclerView rv=d.findViewById(R.id.episodes_rv);rv.setLayoutManager(new LinearLayoutManager(this));EpisodeAdapter a=new EpisodeAdapter(eps,(ep,num)->{selEpisode=num;openPlayer(ci);d.dismiss();},tmdbId,type,selSeason,this);rv.setAdapter(a);((TextView)d.findViewById(R.id.dialog_title)).setText(ci.displayTitle()+" \u2014 S"+selSeason);d.show();}
    private void openPlayer(ContentItem ci){Intent i=new Intent(this,PlayerActivity.class);i.putExtra("type",type);i.putExtra("id",tmdbId);i.putExtra("imdbId",ci.imdbId!=null?ci.imdbId:"");i.putExtra("title",ci.displayTitle());i.putExtra("season",selSeason);i.putExtra("episode",selEpisode);i.putExtra("total_episodes",eps.size());startActivity(i);LibraryManager.updateProgress(this,ci,selSeason,selEpisode,WatchProgress.get(this,tmdbId,type,selSeason,selEpisode));}
    private void refreshBtns(ContentItem ci){boolean fav=LibraryManager.isIn(this,ci.id,ci.mediaType,LibraryManager.FAVORITES);boolean wl=LibraryManager.isIn(this,ci.id,ci.mediaType,LibraryManager.WATCHLIST);b.favoriteBtn.setAlpha(fav?1f:0.4f);b.watchlistBtn.setAlpha(wl?1f:0.4f);}
}
